---
name: File Transfer Tests

on:
  workflow_dispatch:

permissions: {}

env:
  AWS_REGION: ${{ vars.AWS_REGION }}

jobs:
  file-transfer-tests:
    name: Prepare file transfer tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      id-token: write
    steps:
      - name: Harden Runner
        if: github.event.repository.private == false
        uses: step-security/harden-runner@e14015d583714f6e62063499dc959a02595150a1 # v2.21.1
        with:
          egress-policy: audit

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@7474bc4690e29a8392af63c5b98e7449536d5c3a # v4.3.1
        with:
          role-to-assume: arn:aws:iam::${{ vars.ACCOUNT_ID }}:role/modernisation-platform-oidc-cicd
          aws-region: ${{ env.AWS_REGION }}